// Generated by IcedCoffeeScript 1.6.3-d
(function() {
  var _3S;



  _3S = {
    encrypt: function(buffer, opts, cb) {
      return console.log("Encrypting...");
    },
    decrypt: function(buffer, opts, cb) {
      return console.log("Decrypting...");
    }
  };

  exports.encrypt = _3S.encrypt;

  exports.decrypt = _3S.decrypt;

}).call(this);
